#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'odrive-driver','console_scripts','odrive_node'
__requires__ = 'odrive-driver'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('odrive-driver', 'console_scripts', 'odrive_node')()
    )
