#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'ros2-serial-interface','console_scripts','pynput_key_pub'
__requires__ = 'ros2-serial-interface'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('ros2-serial-interface', 'console_scripts', 'pynput_key_pub')()
    )
